
# Mozilla to Wav 1 
wav_dir: "../../data/common_voice_filtered/test/wav"
audio_length_s: 10
parallelize_pro: True
aug_dir: "../../data/augmented/test"
augment_nu: 4
img_dir: "../../data/datasets/test"
feature_type: spectrogram
feature_nu: 90

 # in alphanumeric order
languages: ["english", "french", "german", "spanish"]
